export const PAGE_PERMISSIONS = {
  "/dashboard": 1,
  "/sell/newsell": 2,
  "/sell/pending": 3,
  "/sell/receipt": 4,
  "/sell/roadmap": 5,
  "/sell/history": 6,
  "/customers/add": 7,
  "/customers/manage": 8,
  "/stock/suppliers": 9,
  "/stock/articles": 10,
  "/stock/inventory": 11,
  "/stock/packagings": 12,
  "/stock/packagings/inventory": 13,
  "/stock/lose": 14,
  "/finances/caisse": 15,
  "/finances/expenses": 16,
  "/enterprise/salespoints": 17,
  "/enterprise/informations": 18,
  "/enterprise/users": 19,
  "/reports/all": 20,
};
